### PR TITLE
Increase default timeout

### PR DESCRIPTION
**Pull request by ttuffin**
We [occasionally hit the default timeout](https://github.com/ansible/eda-qa/actions/runs/4763659117/jobs/8467344915?pr=107#step:8:510) during teardown of the decision environments. Increasing to 25s to resolve this for now. Another option is to decrease the amount of decision environments but we can look into this later in need be.

### CODE REVIEW

**Comment by Alex-Izquierdo** [comment]
I was looking and I couldn't find where comes from that 15 seconds, but a quick search in the code can show that the default_timeout is not passed at all there. It must be a coincidence. You need to pass the value to the .wait() call

**Comment by ttuffin** [comment]
> I was looking and I couldn't find where comes from that 15 seconds, but a quick search in the code can show that the default_timeout is not passed at all there. It must be a coincidence. You need to pass the value to the .wait() call

It comes from here: https://github.com/ansible/eda-qa/blob/main/eda_qa/tests/api/test_websocket.py#L7
Webhook test uses timeout to ensure we don't get an indefinite hang on `ws.connect`

**Comment by Alex-Izquierdo** [comment]
mmm, is pytest setting that value at threading module global scope? It sounds like wrong but it is the best hypothesis. I will not look it. Anyway, now that we have this possible sideeffect, precisely because we could user another value there, we need to ensure that the teardown uses the value that we expect. So the .wait() call must have that timeout ;)

**Comment by ttuffin** [comment]
Added

**Review by Alex-Izquierdo — APPROVED** [review]

**Comment by Alex-Izquierdo** [comment]
pff, test suite fails in another place, @ttuffin can you look it, pls?

**Comment by ttuffin** [comment]
> pff, test suite fails in another place, @ttuffin can you look it, pls?

https://github.com/ansible/eda-qa/pull/109

**Pull request merged**
